### ISSUE TITLE
It would be awesome to get a more detailed instruction on how to use your code.

### ISSUE THREAD

**Issue by HeyAshh** [notscuffed/repkg#9]
I personally could really use the functionality you're building. I can do something similar with Python code, but it's tedious.

Good luck with your development! :)

**Comment by notscuffed** [comment]
It's currently not possible to use this code in any language that is not running on CLI (anything else than C#/F#/VisualBasic...) because the compiled dll's are managed and not native.

(Though it is possible to [compile C# to native dll](https://github.com/dotnet/corert/tree/master/samples/NativeLibrary) but that would involve writing another simplified layer on top of the existing code)

If you just want to compile the C# code then all you need is [Visual Studio](https://visualstudio.microsoft.com/vs/) and then open the RePKG.sln file and compile it there. After that you can create your own project and reference the compiled dll's.
